name: Docker

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Exclude pre-releases
    branches:
      - main
      - dockertweaks

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      USER: sdss
      APP: marvin
    steps:
      - name: Set docker tags
        id: set-tags
        run: |
          echo TAG_LATEST=$USER/$APP:latest >> $GITHUB_OUTPUT
          if [[ $GITHUB_REF == refs/heads/main ]]
          then
            echo TAGS=$USER/$APP:latest >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/* ]]
          then
            BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/[\/]/_/g')
            echo TAGS=$USER/$APP:$BRANCH >> $GITHUB_OUTPUT
          else
            echo TAGS=$USER/$APP:${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT
          fi
      - name: Show tags
        run: echo ${{ steps.set-tags.outputs.TAGS }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ steps.set-tags.outputs.TAGS }}
            ghcr.io/${{ steps.set-tags.outputs.TAG_LATEST }}
          file: ./Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}