name: Upload to PyPi

on:
  release:
    types: [published]

jobs:
    build:

        runs-on: ubuntu-latest

        permissions:
          contents: write
          id-token: write

        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install setuptools wheel twine build

            - name: Build package
              run: |
                python -m build

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
